import { requestKeyed } from '../../lookup.ts'
/**
 * What each request message declares, and what each field holds. A body is
 * merged into one of these before the endpoint reads anything, so every name
 * in it is judged here first: a declared field against its own type, and a
 * name the message does not declare against the grammar the merge steps over
 * it with.
 *
 * Generated from the protos, joined with the route table and each
 * servlet's merge target.
 */
export const MESSAGE_FIELDS: Readonly<Record<string, Readonly<Record<string, string>>>> =
  requestKeyed({
    Account: {
      account_name: 'bytes',
      type: 'enum:AccountType',
      address: 'bytes',
      balance: 'int64',
      votes: 'message[]',
      asset: 'message[]',
      frozen: 'message[]',
      net_usage: 'int64',
      create_time: 'int64',
      allowance: 'int64',
      latest_withdraw_time: 'int64',
      acquired_delegated_frozen_balance_for_bandwidth: 'int64',
      delegated_frozen_balance_for_bandwidth: 'int64',
      old_tron_power: 'int64',
      tron_power: 'message',
      asset_optimized: 'bool',
      latest_opration_time: 'int64',
      code: 'bytes',
      is_witness: 'bool',
      is_committee: 'bool',
      frozen_supply: 'message[]',
      asset_issued_name: 'bytes',
      asset_issued_ID: 'bytes',
      latest_asset_operation_time: 'message[]',
      free_net_usage: 'int64',
      free_asset_net_usage: 'message[]',
      latest_consume_time: 'int64',
      latest_consume_free_time: 'int64',
      account_id: 'bytes',
      net_window_size: 'int64',
      net_window_optimized: 'bool',
      account_resource: 'message',
      codeHash: 'bytes',
      owner_permission: 'message',
      witness_permission: 'message',
      active_permission: 'message[]',
      frozenV2: 'message[]',
      unfrozenV2: 'message[]',
      delegated_frozenV2_balance_for_bandwidth: 'int64',
      acquired_delegated_frozenV2_balance_for_bandwidth: 'int64',
      assetV2: 'message[]',
      latest_asset_operation_timeV2: 'message[]',
      free_asset_net_usageV2: 'message[]',
    },
    AccountFrozen: { frozen_balance: 'int64', expire_time: 'int64' },
    AccountResource: {
      energy_usage: 'int64',
      frozen_balance_for_energy: 'message',
      latest_consume_time_for_energy: 'int64',
      acquired_delegated_frozen_balance_for_energy: 'int64',
      delegated_frozen_balance_for_energy: 'int64',
      storage_limit: 'int64',
      storage_usage: 'int64',
      latest_exchange_storage_time: 'int64',
      energy_window_size: 'int64',
      delegated_frozenV2_balance_for_energy: 'int64',
      acquired_delegated_frozenV2_balance_for_energy: 'int64',
      energy_window_optimized: 'bool',
    },
    AccountFreezeV2: { type: 'enum:ResourceCode', amount: 'int64' },
    AccountUnfreezeV2: {
      type: 'enum:ResourceCode',
      unfreeze_amount: 'int64',
      unfreeze_expire_time: 'int64',
    },
    AccountBalanceRequest: { account_identifier: 'message', block_identifier: 'message' },
    AccountCreateContract: {
      owner_address: 'bytes',
      account_address: 'bytes',
      type: 'enum:AccountType',
    },
    AccountPermissionUpdateContract: {
      owner_address: 'bytes',
      owner: 'message',
      witness: 'message',
      actives: 'message[]',
    },
    AccountUpdateContract: { account_name: 'bytes', owner_address: 'bytes' },
    AssetIssueContract: {
      id: 'string',
      owner_address: 'bytes',
      name: 'bytes',
      abbr: 'bytes',
      total_supply: 'int64',
      frozen_supply: 'message[]',
      trx_num: 'int32',
      precision: 'int32',
      num: 'int32',
      start_time: 'int64',
      end_time: 'int64',
      order: 'int64',
      vote_score: 'int32',
      description: 'bytes',
      url: 'bytes',
      free_asset_net_limit: 'int64',
      public_free_asset_net_limit: 'int64',
      public_free_asset_net_usage: 'int64',
      public_latest_free_net_time: 'int64',
    },
    AssetIssueFrozenSupply: { frozen_amount: 'int64', frozen_days: 'int64' },
    BlockIdentifier: { hash: 'bytes', number: 'int64' },
    BlockLimit: { startNum: 'int64', endNum: 'int64' },
    BlockReq: { id_or_num: 'string', detail: 'bool' },
    BytesMessage: { value: 'bytes' },
    // the delegation index servlets read their value as an account address
    DelegatedIndexMessage: { value: 'bytes' },
    CanDelegatedMaxSizeRequestMessage: { type: 'int32', owner_address: 'bytes' },
    CanWithdrawUnfreezeAmountRequestMessage: { owner_address: 'bytes', timestamp: 'int64' },
    CancelAllUnfreezeV2Contract: { owner_address: 'bytes' },
    ClearABIContract: { owner_address: 'bytes', contract_address: 'bytes' },
    CreateSmartContract: {
      owner_address: 'bytes',
      new_contract: 'message',
      call_token_value: 'int64',
      token_id: 'int64',
    },
    DelegateResourceContract: {
      owner_address: 'bytes',
      resource: 'enum:ResourceCode',
      balance: 'int64',
      receiver_address: 'bytes',
      lock: 'bool',
      lock_period: 'int64',
    },
    DelegatedResourceMessage: { fromAddress: 'bytes', toAddress: 'bytes' },
    ExchangeCreateContract: {
      owner_address: 'bytes',
      first_token_id: 'bytes',
      first_token_balance: 'int64',
      second_token_id: 'bytes',
      second_token_balance: 'int64',
    },
    ExchangeInjectContract: {
      owner_address: 'bytes',
      exchange_id: 'int64',
      token_id: 'bytes',
      quant: 'int64',
    },
    ExchangeTransactionContract: {
      owner_address: 'bytes',
      exchange_id: 'int64',
      token_id: 'bytes',
      quant: 'int64',
      expected: 'int64',
    },
    ExchangeWithdrawContract: {
      owner_address: 'bytes',
      exchange_id: 'int64',
      token_id: 'bytes',
      quant: 'int64',
    },
    FreezeBalanceContract: {
      owner_address: 'bytes',
      frozen_balance: 'int64',
      frozen_duration: 'int64',
      resource: 'enum:ResourceCode',
      receiver_address: 'bytes',
    },
    FreezeBalanceV2Contract: {
      owner_address: 'bytes',
      frozen_balance: 'int64',
      resource: 'enum:ResourceCode',
    },
    GetAvailableUnfreezeCountRequestMessage: { owner_address: 'bytes' },
    IvkDecryptTRC20Parameters: {
      start_block_index: 'int64',
      end_block_index: 'int64',
      shielded_TRC20_contract_address: 'bytes',
      ivk: 'bytes',
      ak: 'bytes',
      nk: 'bytes',
    },
    MarketCancelOrderContract: { owner_address: 'bytes', order_id: 'bytes' },
    MarketOrderPair: { sell_token_id: 'bytes', buy_token_id: 'bytes' },
    MarketSellAssetContract: {
      owner_address: 'bytes',
      sell_token_id: 'bytes',
      sell_token_quantity: 'int64',
      buy_token_id: 'bytes',
      buy_token_quantity: 'int64',
    },
    NfTRC20Parameters: {
      note: 'message',
      ak: 'bytes',
      nk: 'bytes',
      position: 'int64',
      shielded_TRC20_contract_address: 'bytes',
    },
    Permission: {
      type: 'enum:PermissionType',
      id: 'int32',
      permission_name: 'string',
      threshold: 'int64',
      parent_id: 'int32',
      operations: 'bytes',
      keys: 'message[]',
    },
    Key: { address: 'bytes', weight: 'int64' },
    NumberMessage: { num: 'int64' },
    OvkDecryptTRC20Parameters: {
      start_block_index: 'int64',
      end_block_index: 'int64',
      ovk: 'bytes',
      shielded_TRC20_contract_address: 'bytes',
    },
    PaginatedMessage: { offset: 'int64', limit: 'int64' },
    ParticipateAssetIssueContract: {
      owner_address: 'bytes',
      to_address: 'bytes',
      asset_name: 'bytes',
      amount: 'int64',
    },
    PrivateShieldedTRC20Parameters: {
      ask: 'bytes',
      nsk: 'bytes',
      ovk: 'bytes',
      from_amount: 'string',
      shielded_spends: 'message[]',
      shielded_receives: 'message[]',
      transparent_to_address: 'bytes',
      to_amount: 'string',
      shielded_TRC20_contract_address: 'bytes',
    },
    PrivateShieldedTRC20ParametersWithoutAsk: {
      ak: 'bytes',
      nsk: 'bytes',
      ovk: 'bytes',
      from_amount: 'string',
      shielded_spends: 'message[]',
      shielded_receives: 'message[]',
      transparent_to_address: 'bytes',
      to_amount: 'string',
      shielded_TRC20_contract_address: 'bytes',
    },
    ProposalApproveContract: {
      owner_address: 'bytes',
      proposal_id: 'int64',
      is_add_approval: 'bool',
    },
    ProposalCreateContract: { owner_address: 'bytes', parameters: 'message[]' },
    ProposalParameter: { key: 'int64', value: 'int64' },
    ProposalDeleteContract: { owner_address: 'bytes', proposal_id: 'int64' },
    SetAccountIdContract: { account_id: 'bytes', owner_address: 'bytes' },
    SmartContract: {
      origin_address: 'bytes',
      contract_address: 'bytes',
      abi: 'message',
      bytecode: 'bytes',
      call_value: 'int64',
      consume_user_resource_percent: 'int64',
      name: 'string',
      origin_energy_limit: 'int64',
      code_hash: 'bytes',
      trx_hash: 'bytes',
      version: 'int32',
    },
    ShieldedTRC20TriggerContractParameters: {
      shielded_TRC20_Parameters: 'message',
      spend_authority_signature: 'message[]',
      amount: 'string',
      transparent_to_address: 'bytes',
    },
    ShieldedTransferContract: {
      transparent_from_address: 'bytes',
      from_amount: 'int64',
      spend_description: 'message[]',
      receive_description: 'message[]',
      binding_signature: 'bytes',
      transparent_to_address: 'bytes',
      to_amount: 'int64',
    },
    SpendDescription: {
      value_commitment: 'bytes',
      anchor: 'bytes',
      nullifier: 'bytes',
      rk: 'bytes',
      zkproof: 'bytes',
      spend_authority_signature: 'bytes',
    },
    ReceiveDescription: {
      value_commitment: 'bytes',
      note_commitment: 'bytes',
      epk: 'bytes',
      c_enc: 'bytes',
      c_out: 'bytes',
      zkproof: 'bytes',
    },
    SpendAuthSigParameters: { ask: 'bytes', tx_hash: 'bytes', alpha: 'bytes' },
    TransferAssetContract: {
      asset_name: 'bytes',
      owner_address: 'bytes',
      to_address: 'bytes',
      amount: 'int64',
    },
    TransferContract: { owner_address: 'bytes', to_address: 'bytes', amount: 'int64' },
    TriggerSmartContract: {
      owner_address: 'bytes',
      contract_address: 'bytes',
      call_value: 'int64',
      data: 'bytes',
      call_token_value: 'int64',
      token_id: 'int64',
    },
    StringInt64MapEntry: { key: 'string', value: 'int64' },
    UnDelegateResourceContract: {
      owner_address: 'bytes',
      resource: 'enum:ResourceCode',
      balance: 'int64',
      receiver_address: 'bytes',
    },
    UnfreezeAssetContract: { owner_address: 'bytes' },
    UnfreezeBalanceContract: {
      owner_address: 'bytes',
      resource: 'enum:ResourceCode',
      receiver_address: 'bytes',
    },
    UnfreezeBalanceV2Contract: {
      owner_address: 'bytes',
      unfreeze_balance: 'int64',
      resource: 'enum:ResourceCode',
    },
    UpdateAssetContract: {
      owner_address: 'bytes',
      description: 'bytes',
      url: 'bytes',
      new_limit: 'int64',
      new_public_limit: 'int64',
    },
    UpdateBrokerageContract: { owner_address: 'bytes', brokerage: 'int32' },
    UpdateEnergyLimitContract: {
      owner_address: 'bytes',
      contract_address: 'bytes',
      origin_energy_limit: 'int64',
    },
    UpdateSettingContract: {
      owner_address: 'bytes',
      contract_address: 'bytes',
      consume_user_resource_percent: 'int64',
    },
    Vote: { vote_address: 'bytes', vote_count: 'int64' },
    VoteAssetContract: {
      owner_address: 'bytes',
      vote_address: 'bytes[]',
      support: 'bool',
      count: 'int32',
    },
    VoteWitnessContract: { owner_address: 'bytes', votes: 'message[]', support: 'bool' },
    WithdrawBalanceContract: { owner_address: 'bytes' },
    WithdrawExpireUnfreezeContract: { owner_address: 'bytes' },
    WitnessCreateContract: { owner_address: 'bytes', url: 'bytes' },
    WitnessUpdateContract: { owner_address: 'bytes', update_url: 'bytes' },
  })

/**
 * The concrete type behind a nested protobuf field.  `MESSAGE_FIELDS` holds
 * its wire kind; this companion table lets the merge walk into the object and
 * apply the same rules to its children.  Map fields are generated protobuf
 * entry messages on this HTTP surface, hence their shared entry schema.
 */
export const MESSAGE_FIELD_TYPES: Readonly<Record<string, Readonly<Record<string, string>>>> =
  requestKeyed({
    Account: {
      votes: 'Vote',
      asset: 'StringInt64MapEntry',
      assetV2: 'StringInt64MapEntry',
      frozen: 'AccountFrozen',
      tron_power: 'AccountFrozen',
      frozen_supply: 'AccountFrozen',
      latest_asset_operation_time: 'StringInt64MapEntry',
      latest_asset_operation_timeV2: 'StringInt64MapEntry',
      free_asset_net_usage: 'StringInt64MapEntry',
      free_asset_net_usageV2: 'StringInt64MapEntry',
      account_resource: 'AccountResource',
      owner_permission: 'Permission',
      witness_permission: 'Permission',
      active_permission: 'Permission',
      frozenV2: 'AccountFreezeV2',
      unfrozenV2: 'AccountUnfreezeV2',
    },
    AccountPermissionUpdateContract: {
      owner: 'Permission',
      witness: 'Permission',
      actives: 'Permission',
    },
    AccountResource: { frozen_balance_for_energy: 'AccountFrozen' },
    AssetIssueContract: { frozen_supply: 'AssetIssueFrozenSupply' },
    CreateSmartContract: { new_contract: 'SmartContract' },
    Permission: { keys: 'Key' },
    ProposalCreateContract: { parameters: 'ProposalParameter' },
    ShieldedTransferContract: {
      spend_description: 'SpendDescription',
      receive_description: 'ReceiveDescription',
    },
    VoteWitnessContract: { votes: 'Vote' },
  })

/**
 * Bytes fields that carry something other than raw bytes. Under `visible` an
 * address is stated in base58 and a name as the text it holds; without it both
 * are hex like every other bytes field.
 */
export const SELF_FORMAT_FIELDS: Readonly<
  Record<string, Readonly<Record<string, 'address' | 'name'>>>
> = requestKeyed({
  Account: {
    account_name: 'name',
    address: 'address',
    asset_issued_name: 'name',
    asset_issued_ID: 'name',
    account_id: 'name',
  },
  Key: { address: 'address' },
  Vote: { vote_address: 'address' },
  AccountCreateContract: { owner_address: 'address', account_address: 'address' },
  AccountPermissionUpdateContract: { owner_address: 'address' },
  AccountUpdateContract: { account_name: 'name', owner_address: 'address' },
  AssetIssueContract: {
    owner_address: 'address',
    name: 'name',
    abbr: 'name',
    description: 'name',
    url: 'name',
  },
  CanDelegatedMaxSizeRequestMessage: { owner_address: 'address' },
  CanWithdrawUnfreezeAmountRequestMessage: { owner_address: 'address' },
  CancelAllUnfreezeV2Contract: { owner_address: 'address' },
  ClearABIContract: { owner_address: 'address', contract_address: 'address' },
  CreateSmartContract: { owner_address: 'address' },
  DelegateResourceContract: { owner_address: 'address', receiver_address: 'address' },
  // Delegation-index queries treat `value` as an account address, not generic bytes.
  // Registered aliases inherit this format through the canonical method's schema.
  DelegatedIndexMessage: { value: 'address' },
  DelegatedResourceMessage: { fromAddress: 'address', toAddress: 'address' },
  ExchangeCreateContract: {
    owner_address: 'address',
    first_token_id: 'name',
    second_token_id: 'name',
  },
  ExchangeInjectContract: { owner_address: 'address', token_id: 'name' },
  ExchangeTransactionContract: { owner_address: 'address', token_id: 'name' },
  ExchangeWithdrawContract: { owner_address: 'address', token_id: 'name' },
  FreezeBalanceContract: { owner_address: 'address', receiver_address: 'address' },
  FreezeBalanceV2Contract: { owner_address: 'address' },
  GetAvailableUnfreezeCountRequestMessage: { owner_address: 'address' },
  MarketCancelOrderContract: { owner_address: 'address' },
  MarketOrderPair: { sell_token_id: 'name', buy_token_id: 'name' },
  MarketSellAssetContract: {
    owner_address: 'address',
    sell_token_id: 'name',
    buy_token_id: 'name',
  },
  ParticipateAssetIssueContract: {
    owner_address: 'address',
    to_address: 'address',
    asset_name: 'name',
  },
  ProposalApproveContract: { owner_address: 'address' },
  ProposalCreateContract: { owner_address: 'address' },
  ProposalDeleteContract: { owner_address: 'address' },
  SetAccountIdContract: { account_id: 'name', owner_address: 'address' },
  SmartContract: { origin_address: 'address', contract_address: 'address' },
  ShieldedTransferContract: {
    transparent_from_address: 'address',
    transparent_to_address: 'address',
  },
  TransferAssetContract: { asset_name: 'name', owner_address: 'address', to_address: 'address' },
  TransferContract: { owner_address: 'address', to_address: 'address' },
  TriggerSmartContract: { owner_address: 'address', contract_address: 'address' },
  UnDelegateResourceContract: { owner_address: 'address', receiver_address: 'address' },
  UnfreezeAssetContract: { owner_address: 'address' },
  UnfreezeBalanceContract: { owner_address: 'address', receiver_address: 'address' },
  UnfreezeBalanceV2Contract: { owner_address: 'address' },
  UpdateAssetContract: { owner_address: 'address', description: 'name', url: 'name' },
  UpdateBrokerageContract: { owner_address: 'address' },
  UpdateEnergyLimitContract: { owner_address: 'address', contract_address: 'address' },
  UpdateSettingContract: { owner_address: 'address', contract_address: 'address' },
  VoteAssetContract: { owner_address: 'address', vote_address: 'address' },
  VoteWitnessContract: { owner_address: 'address' },
  WithdrawBalanceContract: { owner_address: 'address' },
  WithdrawExpireUnfreezeContract: { owner_address: 'address' },
  WitnessCreateContract: { owner_address: 'address', url: 'name' },
  WitnessUpdateContract: { owner_address: 'address', update_url: 'name' },
})

/**
 * The message a registered definition merges its whole body into. Aliases inherit
 * the canonical entry through Registry; independent servlets keep their own entry.
 * Unimplemented protocol routes retain their schema declarations. An absent entry reads
 * its parameters by name instead and never walks the body.
 */
export const MERGED_MESSAGE: Readonly<Record<string, string>> = requestKeyed({
  'wallet/accountpermissionupdate': 'AccountPermissionUpdateContract',
  'wallet/cancelallunfreezev2': 'CancelAllUnfreezeV2Contract',
  'wallet/clearabi': 'ClearABIContract',
  'wallet/createaccount': 'AccountCreateContract',
  'wallet/createassetissue': 'AssetIssueContract',
  'wallet/createshieldedcontractparameters': 'PrivateShieldedTRC20Parameters',
  'wallet/createshieldedcontractparameterswithoutask': 'PrivateShieldedTRC20ParametersWithoutAsk',
  'wallet/createspendauthsig': 'SpendAuthSigParameters',
  'wallet/createtransaction': 'TransferContract',
  'wallet/createwitness': 'WitnessCreateContract',
  'wallet/delegateresource': 'DelegateResourceContract',
  'wallet/exchangecreate': 'ExchangeCreateContract',
  'wallet/exchangeinject': 'ExchangeInjectContract',
  'wallet/exchangetransaction': 'ExchangeTransactionContract',
  'wallet/exchangewithdraw': 'ExchangeWithdrawContract',
  'wallet/freezebalance': 'FreezeBalanceContract',
  'wallet/freezebalancev2': 'FreezeBalanceV2Contract',
  'wallet/getaccount': 'Account',
  'wallet/getaccountbalance': 'AccountBalanceRequest',
  'wallet/getaccountbyid': 'Account',
  'wallet/getaccountnet': 'Account',
  'wallet/getakfromask': 'BytesMessage',
  'wallet/getassetissuebyaccount': 'Account',
  'wallet/getavailableunfreezecount': 'GetAvailableUnfreezeCountRequestMessage',
  'wallet/getblock': 'BlockReq',
  'wallet/getblockbalance': 'BlockIdentifier',
  'wallet/getblockbyid': 'BytesMessage',
  'wallet/getblockbylatestnum': 'NumberMessage',
  'wallet/getblockbylimitnext': 'BlockLimit',
  'wallet/getblockbynum': 'NumberMessage',
  'wallet/getcandelegatedmaxsize': 'CanDelegatedMaxSizeRequestMessage',
  'wallet/getcanwithdrawunfreezeamount': 'CanWithdrawUnfreezeAmountRequestMessage',
  'wallet/getcontract': 'BytesMessage',
  'wallet/getcontractinfo': 'BytesMessage',
  'wallet/getdelegatedresource': 'DelegatedResourceMessage',
  'wallet/getdelegatedresourceaccountindex': 'DelegatedIndexMessage',
  'wallet/getdelegatedresourceaccountindexv2': 'DelegatedIndexMessage',
  'wallet/getdelegatedresourcev2': 'DelegatedResourceMessage',
  'wallet/getexpandedspendingkey': 'BytesMessage',
  'wallet/getmarketorderbyid': 'BytesMessage',
  'wallet/getmarketorderlistbypair': 'MarketOrderPair',
  'wallet/getmarketpricebypair': 'MarketOrderPair',
  'wallet/getnkfromnsk': 'BytesMessage',
  'wallet/getpaginatedassetissuelist': 'PaginatedMessage',
  'wallet/getpaginatedexchangelist': 'PaginatedMessage',
  'wallet/getpaginatednowwitnesslist': 'PaginatedMessage',
  'wallet/getpaginatedproposallist': 'PaginatedMessage',
  'wallet/gettransactionbyid': 'BytesMessage',
  'wallet/gettransactioncountbyblocknum': 'NumberMessage',
  'wallet/gettransactionfrompending': 'BytesMessage',
  'wallet/gettransactioninfobyblocknum': 'NumberMessage',
  'wallet/gettransactioninfobyid': 'BytesMessage',
  'wallet/gettransactionreceiptbyid': 'BytesMessage',
  'wallet/gettriggerinputforshieldedtrc20contract': 'ShieldedTRC20TriggerContractParameters',
  'wallet/isshieldedtrc20contractnotespent': 'NfTRC20Parameters',
  'wallet/marketcancelorder': 'MarketCancelOrderContract',
  'wallet/marketsellasset': 'MarketSellAssetContract',
  'wallet/participateassetissue': 'ParticipateAssetIssueContract',
  'wallet/proposalapprove': 'ProposalApproveContract',
  'wallet/proposalcreate': 'ProposalCreateContract',
  'wallet/proposaldelete': 'ProposalDeleteContract',
  'wallet/scanshieldedtrc20notesbyivk': 'IvkDecryptTRC20Parameters',
  'wallet/scanshieldedtrc20notesbyovk': 'OvkDecryptTRC20Parameters',
  'wallet/setaccountid': 'SetAccountIdContract',
  'wallet/transferasset': 'TransferAssetContract',
  'wallet/undelegateresource': 'UnDelegateResourceContract',
  'wallet/unfreezeasset': 'UnfreezeAssetContract',
  'wallet/unfreezebalance': 'UnfreezeBalanceContract',
  'wallet/unfreezebalancev2': 'UnfreezeBalanceV2Contract',
  'wallet/updateBrokerage': 'UpdateBrokerageContract',
  'wallet/updateaccount': 'AccountUpdateContract',
  'wallet/updateasset': 'UpdateAssetContract',
  'wallet/updateenergylimit': 'UpdateEnergyLimitContract',
  'wallet/updatesetting': 'UpdateSettingContract',
  'wallet/updatewitness': 'WitnessUpdateContract',
  'wallet/votewitnessaccount': 'VoteWitnessContract',
  'wallet/withdrawbalance': 'WithdrawBalanceContract',
  'wallet/withdrawexpireunfreeze': 'WithdrawExpireUnfreezeContract',
  'walletsolidity/getpaginatednowwitnesslist': 'PaginatedMessage',
  'walletsolidity/isshieldedtrc20contractnotespent': 'NfTRC20Parameters',
  'walletsolidity/scanshieldedtrc20notesbyivk': 'IvkDecryptTRC20Parameters',
  'walletsolidity/scanshieldedtrc20notesbyovk': 'OvkDecryptTRC20Parameters',
})

/** the members of every enum a request field carries */
export const MERGE_ENUMS: Readonly<Record<string, Readonly<Record<string, number>>>> = requestKeyed(
  {
    AccountType: { Normal: 0, AssetIssue: 1, Contract: 2 },
    PermissionType: { Owner: 0, Witness: 1, Active: 2 },
    ResourceCode: { BANDWIDTH: 0, ENERGY: 1, TRON_POWER: 2 },
  },
)

/** the fully qualified name a merge failure states an enum by */
export const MERGE_ENUM_NAMES: Readonly<Record<string, string>> = requestKeyed({
  AccountType: 'protocol.AccountType',
  PermissionType: 'protocol.Permission.PermissionType',
  ResourceCode: 'protocol.ResourceCode',
})
