import { requestKeyed } from '../../lookup.ts'
/**
 * The wallet-surface route table. The value is which of `doGet` / `doPost`
 * the route's servlet overrides:
 *
 * - `B` — both, so either verb reaches the servlet
 * - `S` — `doGet` is an empty method body, so a GET answers 200 with no body
 * - `P` — `doPost` only; the container answers 405 for every other verb
 * - `G` — `doGet` only
 *
 * Two things read this table. One is telling "the surface has no such path"
 * (404) apart from "this node does not serve it" (501). The other is deciding
 * what a given verb gets at a given endpoint, before any handler runs.
 *
 * Regenerate it against a new chain release: the lines that change are the
 * routes that release added, dropped, or gave a new set of verbs.
 */
import type { RouteKind } from '../httpDialect.ts'

export const JAVA_TRON_ROUTES: Readonly<Record<string, RouteKind>> = requestKeyed({
  'monitor/getnodeinfo': 'B',
  'monitor/getstatsinfo': 'G',
  'net/listnodes': 'B',
  'wallet/accountpermissionupdate': 'S',
  'wallet/broadcasthex': 'P',
  'wallet/broadcasttransaction': 'P',
  'wallet/cancelallunfreezev2': 'P',
  'wallet/clearabi': 'S',
  'wallet/createCommonTransaction': 'P',
  'wallet/createaccount': 'P',
  'wallet/createassetissue': 'S',
  'wallet/createshieldedcontractparameters': 'S',
  'wallet/createshieldedcontractparameterswithoutask': 'S',
  'wallet/createspendauthsig': 'S',
  'wallet/createtransaction': 'S',
  'wallet/createwitness': 'S',
  'wallet/delegateresource': 'P',
  'wallet/deploycontract': 'S',
  'wallet/estimateenergy': 'S',
  'wallet/exchangecreate': 'P',
  'wallet/exchangeinject': 'P',
  'wallet/exchangetransaction': 'P',
  'wallet/exchangewithdraw': 'P',
  'wallet/freezebalance': 'P',
  'wallet/freezebalancev2': 'P',
  'wallet/getBrokerage': 'B',
  'wallet/getReward': 'B',
  'wallet/getaccount': 'B',
  'wallet/getaccountbalance': 'P',
  'wallet/getaccountbyid': 'B',
  'wallet/getaccountnet': 'B',
  'wallet/getaccountresource': 'B',
  'wallet/getakfromask': 'B',
  'wallet/getapprovedlist': 'S',
  'wallet/getassetissuebyaccount': 'B',
  'wallet/getassetissuebyid': 'B',
  'wallet/getassetissuebyname': 'B',
  'wallet/getassetissuelist': 'B',
  'wallet/getassetissuelistbyname': 'B',
  'wallet/getavailableunfreezecount': 'B',
  'wallet/getbandwidthprices': 'B',
  'wallet/getblock': 'B',
  'wallet/getblockbalance': 'P',
  'wallet/getblockbyid': 'B',
  'wallet/getblockbylatestnum': 'B',
  'wallet/getblockbylimitnext': 'B',
  'wallet/getblockbynum': 'B',
  'wallet/getburntrx': 'B',
  'wallet/getcandelegatedmaxsize': 'B',
  'wallet/getcanwithdrawunfreezeamount': 'B',
  'wallet/getchainparameters': 'B',
  'wallet/getcontract': 'B',
  'wallet/getcontractinfo': 'B',
  'wallet/getdelegatedresource': 'B',
  'wallet/getdelegatedresourceaccountindex': 'B',
  'wallet/getdelegatedresourceaccountindexv2': 'B',
  'wallet/getdelegatedresourcev2': 'B',
  'wallet/getdiversifier': 'B',
  'wallet/getenergyprices': 'B',
  'wallet/getexchangebyid': 'B',
  'wallet/getexpandedspendingkey': 'B',
  'wallet/getincomingviewingkey': 'B',
  'wallet/getmarketorderbyaccount': 'B',
  'wallet/getmarketorderbyid': 'B',
  'wallet/getmarketorderlistbypair': 'B',
  'wallet/getmarketpairlist': 'B',
  'wallet/getmarketpricebypair': 'B',
  'wallet/getmemofee': 'B',
  'wallet/getnewshieldedaddress': 'B',
  'wallet/getnextmaintenancetime': 'B',
  'wallet/getnkfromnsk': 'B',
  'wallet/getnodeinfo': 'B',
  'wallet/getnowblock': 'B',
  'wallet/getpaginatedassetissuelist': 'B',
  'wallet/getpaginatedexchangelist': 'B',
  'wallet/getpaginatednowwitnesslist': 'B',
  'wallet/getpaginatedproposallist': 'B',
  'wallet/getpendingsize': 'B',
  'wallet/getproposalbyid': 'B',
  'wallet/getrcm': 'B',
  'wallet/getsignweight': 'S',
  'wallet/getspendingkey': 'B',
  'wallet/gettransactionbyid': 'B',
  'wallet/gettransactioncountbyblocknum': 'B',
  'wallet/gettransactionfrompending': 'B',
  'wallet/gettransactioninfobyblocknum': 'B',
  'wallet/gettransactioninfobyid': 'B',
  'wallet/gettransactionlistfrompending': 'B',
  'wallet/gettransactionreceiptbyid': 'B',
  'wallet/gettriggerinputforshieldedtrc20contract': 'S',
  'wallet/getzenpaymentaddress': 'B',
  'wallet/isshieldedtrc20contractnotespent': 'S',
  'wallet/listexchanges': 'B',
  'wallet/listnodes': 'B',
  'wallet/listproposals': 'B',
  'wallet/listwitnesses': 'B',
  'wallet/marketcancelorder': 'S',
  'wallet/marketsellasset': 'S',
  'wallet/participateassetissue': 'S',
  'wallet/proposalapprove': 'S',
  'wallet/proposalcreate': 'S',
  'wallet/proposaldelete': 'S',
  'wallet/scanshieldedtrc20notesbyivk': 'B',
  'wallet/scanshieldedtrc20notesbyovk': 'B',
  'wallet/setaccountid': 'S',
  'wallet/totaltransaction': 'B',
  'wallet/transferasset': 'S',
  'wallet/triggerconstantcontract': 'S',
  'wallet/triggersmartcontract': 'S',
  'wallet/undelegateresource': 'S',
  'wallet/unfreezeasset': 'S',
  'wallet/unfreezebalance': 'S',
  'wallet/unfreezebalancev2': 'S',
  'wallet/updateBrokerage': 'P',
  'wallet/updateaccount': 'S',
  'wallet/updateasset': 'S',
  'wallet/updateenergylimit': 'S',
  'wallet/updatesetting': 'S',
  'wallet/updatewitness': 'S',
  'wallet/validateaddress': 'B',
  'wallet/votewitnessaccount': 'S',
  'wallet/withdrawbalance': 'S',
  'wallet/withdrawexpireunfreeze': 'S',
  'walletsolidity/estimateenergy': 'S',
  'walletsolidity/getBrokerage': 'B',
  'walletsolidity/getReward': 'B',
  'walletsolidity/getaccount': 'B',
  'walletsolidity/getaccountbyid': 'B',
  'walletsolidity/getassetissuebyid': 'B',
  'walletsolidity/getassetissuebyname': 'B',
  'walletsolidity/getassetissuelist': 'B',
  'walletsolidity/getassetissuelistbyname': 'B',
  'walletsolidity/getavailableunfreezecount': 'B',
  'walletsolidity/getbandwidthprices': 'B',
  'walletsolidity/getblock': 'B',
  'walletsolidity/getblockbyid': 'B',
  'walletsolidity/getblockbylatestnum': 'B',
  'walletsolidity/getblockbylimitnext': 'B',
  'walletsolidity/getblockbynum': 'B',
  'walletsolidity/getburntrx': 'B',
  'walletsolidity/getcandelegatedmaxsize': 'B',
  'walletsolidity/getcanwithdrawunfreezeamount': 'B',
  'walletsolidity/getdelegatedresource': 'B',
  'walletsolidity/getdelegatedresourceaccountindex': 'B',
  'walletsolidity/getdelegatedresourceaccountindexv2': 'B',
  'walletsolidity/getdelegatedresourcev2': 'B',
  'walletsolidity/getenergyprices': 'B',
  'walletsolidity/getexchangebyid': 'B',
  'walletsolidity/getmarketorderbyaccount': 'B',
  'walletsolidity/getmarketorderbyid': 'B',
  'walletsolidity/getmarketorderlistbypair': 'B',
  'walletsolidity/getmarketpairlist': 'B',
  'walletsolidity/getmarketpricebypair': 'B',
  'walletsolidity/getnodeinfo': 'B',
  'walletsolidity/getnowblock': 'B',
  'walletsolidity/getpaginatedassetissuelist': 'B',
  'walletsolidity/getpaginatednowwitnesslist': 'B',
  'walletsolidity/gettransactionbyid': 'B',
  'walletsolidity/gettransactioncountbyblocknum': 'B',
  'walletsolidity/gettransactioninfobyblocknum': 'B',
  'walletsolidity/gettransactioninfobyid': 'B',
  'walletsolidity/isshieldedtrc20contractnotespent': 'S',
  'walletsolidity/listexchanges': 'B',
  'walletsolidity/listwitnesses': 'B',
  'walletsolidity/scanshieldedtrc20notesbyivk': 'B',
  'walletsolidity/scanshieldedtrc20notesbyovk': 'B',
  'walletsolidity/triggerconstantcontract': 'S',
})
